### ISSUE TITLE
前辈你好

### ISSUE THREAD

**Issue by matrixkeygit** [timandy/linq#1]
前辈你好，我从C#转java1年多，一直陆续在写一些utils，初衷也是希望写java代码时能更简洁优雅，特别是对集合数组的操作。最近一周刚开始写java linq，底层操作api基本都实现了。昨晚刚准备提供1个包装层，也想好命名Linq，暴露1个asEnumber的路口。。。
想着java轮子多特地一搜，结果搜到前辈的大作。
粗略看了前辈的源码，简直太棒了。甚至连对Action012、Function012的封装命名都惊人的一致。。
前辈的代码真规范，结构也非常清晰，让我非常喜欢和敬仰。
这么好的开源项目，居然只有10个star！太不科学了！
非常想认识前辈，不知是否有幸。

**Comment by timandy** [comment]
@matrixkeygit    工作略忙，刚看到消息，见谅。
    我也是从 c#转到 java，苦于stream api 的不友好，才将c# 的linq to objects 迁移到 java 平台。
    代码逻辑主要参考 frame work 的源码，部分代码参考 linq4j ，结构在尽量保持和 frame work 一致的前提下进行优化和修改。.net core 的 linq to objects 封装的要更好一些，精力和时间有限，并没有转完。
    最后可以给我发邮件，互相学习，共同进步。
