### ISSUE TITLE
有没有详细点的文档

### ISSUE THREAD

**Issue by 1025431504** [timandy/linq#16]
有些方法光看名字不知道咋用

**Comment by huangye123** [comment]
我希望可以有更详细点的文档说明

**Comment by timandy** [comment]
@1025431504 @huangye123 欢迎提出建议，目前可供参考的使用文档可以参考c# linq to objects的相关文档。本项目文档也在计划中，会慢慢完善。

**Comment by dsp6414** [comment]
完整看了测试代码，和Csharp代码基本一致，向up主点赞👍
