### ISSUE TITLE
常试List泛型对象进行linq查询无效

### ISSUE THREAD

**Issue by riancy** [timandy/linq#2]
List<StockExcelInitMaterial_Entity> list = Linq.asEnumerable(ss)
                			.where(w -> w.getMaterialName().contains(sName))
                			.toList();

list为0，为什么？ss也是List<StockExcelInitMaterial_Entity>对象

**Comment by timandy** [comment]
请调试下 ss 长度是否本身为 0 或 没有符合条件的数据
