### ISSUE TITLE
性能如何？

### ISSUE THREAD

**Issue by kiwimg** [timandy/linq#70]
性能如何？

**Comment by timandy** [comment]
@kiwimg 设计和实现逻辑上对标 c# linq，部分基准测试参见我的 [linq-perf](https://github.com/timandy/linq-perf) 库。

**Comment by kiwimg** [comment]
会持续开发下去吗？会支持Linqtosql?

**Comment by timandy** [comment]
@kiwimg 
1. 我有时间会进行迭代。
2. 暂时不支持linq to sql,因为涉及到表达式树解析，java没有成熟方案。jinq 虽然实现了但生产环境不敢轻易尝试，所以暂不打算做这件事，这个库的目标就是简化集合操作。
