### ISSUE TITLE
linq library .jar

### ISSUE THREAD

**Issue by detectivejd** [timandy/linq#76]
Hi, how are you? I hope that you are good, I am interested about this repository and I have a question:

Do your have a .jar library about this project? it would be very useful to community and if you talk with oracle developers, you repository will be an official java module in the next jdk versions.

I wait your answer.

Greetings.

**Comment by timandy** [comment]
@detectivejd Thanks for your sugguestions. Many of the algorithms in this repository are derived from .net, which may involve copyright issues.
The jar file can be found in the maven repo [https://repo1.maven.org/maven2/com/bestvike/linq/5.0.0/linq-5.0.0.jar](https://repo1.maven.org/maven2/com/bestvike/linq/5.0.0/linq-5.0.0.jar)

**Comment by detectivejd** [comment]
Ok, you can put on the javadoc that your algorithms are based on .net from microsoft, if the oracle corporation offers you money then you can to give a percent to microsoft and with that you won´t have copyright issues.

Now, I recommend you delete the stream and parellelStream due to your linq library may replace the stream functions.

I watched your readme but I didn´t found a manual or example to use your library with data structures or arrays.

I wait your answer.

Greetings.

**Comment by timandy** [comment]
> I watched your readme but I didn´t found a manual or example to use your library with data structures or arrays.

@detectivejd Thanks for your recommand, I am too busy to do that things.  You are welcome contact me if you have any ideas.
The examples can be found in testcases. feel your free.
