### ISSUE TITLE
DebugView Not Working in Intellij

### ISSUE THREAD

**Issue by debraj-manna** [timandy/linq#78]
I have followed the instructions mentioned [here](https://github.com/timandy/linq) for setting up the debug view in Intellij.

But I am getting the below error

<img width="611" alt="Screenshot 2023-07-03 at 10 57 16 PM" src="https://github.com/timandy/linq/assets/8141860/eb6e4f91-1be9-4ac2-8052-8f7d7106172d">

My debugger settings are like below

<img width="747" alt="Screenshot 2023-07-03 at 10 57 34 PM" src="https://github.com/timandy/linq/assets/8141860/2acb15de-5914-4e8b-8b79-d20a061f3ed3">

Can someone suggest what is going wrong?

- Intellij IDEA 2022.1.4
- linq - 5.0.0

**Comment by timandy** [comment]
@debraj-manna  Make sure imported linq in your project.

![image](https://github.com/timandy/linq/assets/3809541/4064e0e5-30f7-47aa-bf40-bdb3660db106)

- IntelliJ IDEA 2023.1.3
- linq - 5.0.0
