### ISSUE TITLE
为什么会有一定断言失败的场景代码

### ISSUE THREAD

**Issue by Linuxea** [timandy/linq#82]
[code](https://github.com/timandy/linq/blob/v2.0.0/src/main/java/com/bestvike/linq/enumerable/_Partition.java#L343)

请问这个断言的目的是什么？

因为我在单元测试发现断言异常，而普通运行时却没有问题。最后查看您的代码，发现是单元测试的开启了断言导致的。
但是想不明白，这个断言是一定会失败的，想不出它的目的究竟是什么？

**Comment by Linuxea** [comment]
## 补充单元测试代码如下：

```java
    @Test
    public void test1() {
        List<String> strings = new ArrayList<>();
        strings.add("1");
        strings.add("2");
        List<String> list = Linq.asEnumerable(strings).where(it -> !it.isEmpty()).take(10).toList();
        System.out.println(list);
    }
```

执行结果：

![image](https://github.com/timandy/linq/assets/18577499/9659d927-cc22-443c-b91a-7a777441c02a)

**Comment by timandy** [comment]
@Linuxea 请使用最新版测试一下

**Comment by Linuxea** [comment]
> @Linuxea 请使用最新版测试一下

你好。最新版本不会，语法也有些许不同<code>Linq.of(..) </code>  而且看起来代码不会触发这种场景。
只是当时没想通为什么会在开始的旧版本中有这种设计。 @timandy

**Comment by timandy** [comment]
@Linuxea 仅在测试时进行验证条件, 运行时不验证, 以提升性能
